@echo off
echo Activating virtual environment...
call venv\Scripts\activate
echo Virtual environment activated.
echo Installing Dependencies...
pip install -r requirements.txt
echo Running 'python manage.py' command...
python manage.py tailwind start
pause
