# Generated by Django 4.2.6 on 2024-05-19 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BlogApp', '0003_blogpost_intro_alter_blogpost_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='color',
            field=models.CharField(choices=[('red', 'red'), ('orange', 'orange'), ('yellow', 'yellow'), ('green', 'green'), ('teal', 'teal'), ('blue', 'blue'), ('indigo', 'indigo'), ('purple', 'purple'), ('pink', 'pink'), ('gray', 'gray')], default='red', max_length=6),
        ),
    ]
