# Generated by Django 4.2.6 on 2024-05-22 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BlogApp', '0004_blogpost_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='title_length',
            field=models.IntegerField(default=0),
        ),
    ]
